/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'VerifyOtp': ApiRouteHandler<{ email?: string; mobile?: string; otp: string }, ApiResponse<200, { status: string; token: string; user: { id: string; name?: string | unknown; email?: string | unknown; mobile?: string | unknown; emailVerified?: boolean; mobileVerified?: boolean; role: 'USER' | 'ADMIN'; status: 'ACTIVE' | 'BLOCKED'; createdAt: string } }> | ApiResponse<400, { error: string }> | ApiResponse<401, { error: string }>, { topic: 'auth.otp_login_succeeded'; data: { userId: string; email?: string | unknown; mobile?: string | unknown; verifiedAt: string } }>
    'RequestOtp': ApiRouteHandler<{ email?: string; mobile?: string }, ApiResponse<200, { status: string; channel: 'email' | 'mobile'; requestedAt: string }> | ApiResponse<400, { error: string }>, never>
    'OtpLoginSucceeded': EventHandler<{ userId: string; email?: string | unknown; mobile?: string | unknown; verifiedAt: string }, never>
  }
    
}